/*UN CAMPO ES UNA COLUMNA DE UNA TABLA Y UN REGISTRO ES UNA FILA DE LA COLUMNA */
/*COMANDO PARA CREAR MI BASE DE DATOS*/
create database miprimerabasededatos;

/*COMANDO PARA VER REGISTRO DE TODAS LAS BASES DE DATOS QUE EXISTEN Y QUE MYSQL SE ENCUENTRA GESTIONANDO*/
show databases;

/*COMANDO PARA ASIGNAR EN QUE BASE DE DATOS VAMOS A TRABAJAR*/
use miprimerabasededatos;

/*COMANDO PARA CREAR UNA TABLA*/
CREATE TABLE animales (
id int, 
nombre varchar(255),
edad int,
estado varchar(255),
PRIMARY KEY (id)
);

/*COMANDO PARA INSERTAR DATOS DENTRO DE UNA TABLA*/
INSERT INTO animales(nombre, estado) VALUES ('chanchito', 'feliz');

/*COMANDO PARA MODIFICAR UNA TABLA QUE YA HA SIDO CREADA*/
ALTER TABLE animales MODIFY COLUMN id int auto_increment;

/*COMANDO PARA DUPLICAR UNA TABLA BASICAMENTE(SHOW CREATE TABLE)*/
SHOW CREATE TABLE animales;

/*RESULTADO AL MOMENTO DE UTILIZAR EL COMANDO SHOW CREATE TABLE: */
CREATE TABLE `animales` (
   `id` int NOT NULL AUTO_INCREMENT,
   `nombre` varchar(255) DEFAULT NULL,
   `edad` int DEFAULT NULL,
   `estado` varchar(255) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ;
 
INSERT INTO animales(nombre, estado) VALUES ('chanchito', 'feliz');
INSERT INTO animales(nombre, estado) VALUES ('dragon', 'feliz');
INSERT INTO animales(nombre, estado) VALUES ('perro', 'feliz');


/*COMANDO QUE PERMITE SELECCIONAR O REALIZAR CONSULTAS DE ELEMENTOS QUE ESTAN DENTRO DE UNA TABLA.*/
SELECT * FROM animales;

/*SI QUEREMOS SELECCIONAR UN REGISTRO DEBEMOS HACER ESTO (HACEMOS USO DEL COMANDO WHERE): */
SELECT * FROM animales WHERE id = 1;
/*SI QUEREMOS ANADIR O AGREGAR OTRA CONDICION A NUESTRA BUSQUEDA (HACEMOS USO DEL COMANDO AND): */
SELECT * FROM animales WHERE estado = 'feliz'AND tipo = 'chanchito';


/*LO QUE ESTAMOS HACIENDO ES ACTUALIZANDO EL ESTADO DE LOS ANIMALES QUE CONTIENEN EL ID (2,3): */
UPDATE animales SET estado = 'triste' where id= 2;
UPDATE animales SET estado = 'triste' where id= 3;

/*VERIFICAMOS NUESTROS REGISTROS: */
SELECT * FROM animales;

/*SI QUIERO USAR EL COMANDO (UPDATE O DETELE) NO PUEDO HACERLO MEDIANTE EL ESTADO O CUALQUIER OTRO ELEMENTO DE LA TABLA, SI O SI PARA QUE ME DEJE DEBE SER MEDIANTE EL ID: */
DELETE FROM animales WHERE id=2;

SELECT * FROM animales;

/*ACTUALIZAR UN ELEMENTO DE LA TABLA MEDIANTE EL ID. */
UPDATE animales set estado = 'triste' WHERE id= 4;

SELECT * FROM animales;