/*UN CAMPO ES UNA COLUMNA DE UNA TABLA Y UN REGISTRO ES UNA FILA DE LA COLUMNA */
/*COMANDO PARA CREAR MI BASE DE DATOS*/
create database miprimerabasededatos;

/*COMANDO PARA VER REGISTRO DE TODAS LAS BASES DE DATOS QUE EXISTEN Y QUE MYSQL SE ENCUENTRA GESTIONANDO*/
show databases;

/*COMANDO PARA ASIGNAR EN QUE BASE DE DATOS VAMOS A TRABAJAR*/
use miprimerabasededatos;

/*COMANDO PARA CREAR UNA TABLA*/
CREATE TABLE animales (
id int, 
nombre varchar(255),
edad int,
estado varchar(255),
PRIMARY KEY (id)
);

/*COMANDO PARA INSERTAR DATOS DENTRO DE UNA TABLA*/
INSERT INTO animales(nombre, estado) VALUES ('chanchito', 'feliz');

/*COMANDO PARA MODIFICAR UNA TABLA QUE YA HA SIDO CREADA*/
ALTER TABLE animales MODIFY COLUMN id int auto_increment;

